#pragma once

/**
 * 1. Anatomical Sockets for Body Parts
 */
enum class bodySlot
{
    HAIR, HEAD, EYES, EARS, MOUTH, NECK,
    HORNS, ANTENNAE,
    TORSO, BREASTS, NIPPLES, STOMACH, BACK,
    ARMS, HANDS, FINGERS,
    HIPS, GROIN, ASS, TAIL,
    LEGS, FEET,
    WINGS, TENTACLES
};

/**
 * 2. Main UI Equipment Grid Slots (6x6 Grid Mapping)
 */
enum class equipSlot
{
    HEADWEAR, EYEWEAR, MOUTHWEAR, NECKWEAR,
    SHOULDERS, TORSO_UNDER, TORSO_OVER,
    CHEST_WEAR, STOMACH_WEAR,
    WRISTS, HANDS, FINGER_PRIMARY, FINGER_SECONDARY,
    HIPS_WEAR, GROIN_UNDER, GROIN_OVER,
    LEGS_INNER, LEGS_OUTER, FEET,
    HORNS_SLOT, WINGS_SLOT, TAIL_SLOT,
    WEAPON_MAIN, WEAPON_OFF,
    PIERCING_EAR, PIERCING_NOSE, PIERCING_LIP,
    PIERCING_NIPPLE, PIERCING_NAVEL, PIERCING_GENITAL,
    NONE
};

/**
 * 3. Alternate UI Grid Sockets for Body Tattoos
 */
enum class tattooSlot
{
    FACE, NECK,
    CHEST, BREASTS, STOMACH, BACK,
    SHOULDERS, ARM_LEFT, ARM_RIGHT, HANDS,
    HIPS, GROIN, ASS,
    LEG_LEFT, LEG_RIGHT, FEET,
    NONE
};

/**
 * 4. Magic Effect Categories
 */
enum class effectType
{
    STAT_MODIFIER,
    TRANSFORMATION,
    COSMETIC_FLAG
};